exec(open("RUN_test/nodes.dr").read())
mySimObject.model.capacitor.setCapacitance(1)
print("Capacitance: {}".format(mySimObject.model.capacitor.getCapacitance()))
mySimObject.model.potential.setSourcePotential(1)
print("Source potential: {}".format(mySimObject.model.potential.getSourcePotential()))
mySimObject.model.conductor.setDefaultConductivity(1)
print("Conductivity: {}".format(mySimObject.model.potential.getEffectiveConductivity()))
trick.stop(10.0)
